resources:
  - name: web
    type: git
    source:
      uri: https://github.com/leungandrew/allocations
      paths:
        - web
      branch: master
  - name: server
    type: git
    source:
      uri: https://github.com/leungandrew/allocations
      paths:
        - server
      branch: master
  - name: cf
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-space))

jobs:
  - name: test-web
    plan:
      - get: web
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "alpine"
          inputs:
            - name: web
          run:
            path: sh
            args:
            - -exc
            - |
              cd web/web
              yarn install
              CI=true yarn test
  - name: deploy-web
    plan:
      - get: web
        trigger: true
        passed: [test-web]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "alpine"
          inputs:
            - name: web
          outputs:
            - name: build
          params:
            REACT_APP_GRAPHQL_URI: ((server-url))
          run:
            path: sh
            args:
            - -exc
            - |
              cd web/web
              yarn install
              yarn build
              cp -rf build/* ../../build/
              cp manifest.yml ../../build/
              cp Staticfile ../../build/
      - put: cf
        params:
          manifest: build/manifest.yml
          path: build
          current_app_name: ((allocations-web))

  - name: test-server
    plan:
      - get: server
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "alpine"
          inputs:
            - name: server
          run:
            path: sh
            args:
            - -exc
            - |
              cd server/server
              yarn install
              CI=true yarn test
  - name: deploy-server
    plan:
      - get: server
        trigger: true
        passed: [test-server]
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "alpine"
          inputs:
            - name: server
          params:
            FIREBASE_TOKEN: ((firebase-token))
            FIREBASE_PROJECT_ID: ((firebase-project-id))
            FIREBASE_AUTH_DOMAIN: ((firebase-auth-domain))
            FIREBASE_API_KEY: ((firebase-api-key))
          run:
            path: sh
            args:
            - -exc
            - |
              cd server/server
              yarn install
              yarn funcs:deploy-ci
  - name: test-functional
    plan:
      - get: web
        passed: [deploy-web]
        trigger: true
      - get: server
        passed: [deploy-server]
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: testcafe/testcafe
          inputs:
            - name: web
          run:
            path: sh
            args:
              - -exc
              - |
                cd web/functional-tests
                /opt/testcafe/docker/testcafe-docker.sh firefox test.js
