resources:
  - name: web
    type: git
    source:
      uri: https://github.com/leungandrew/allocations
      paths:
        - web
      branch: master
  - name: server
    type: git
    source:
      uri: https://github.com/leungandrew/allocations
      paths:
        - server
      branch: master

jobs:
  - name: test-web
    plan:
      - get: web
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "alpine"
          inputs:
            - name: web
          run:
            path: sh
            args:
            - -exc
            - |
              cd web/web
              yarn install
              CI=true yarn test
  - name: test-server
    plan:
      - get: server
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "alpine"
          inputs:
            - name: server
          run:
            path: sh
            args:
            - -exc
            - |
              cd server/server
              yarn install
              CI=true yarn test
